
# Site configuration

targets:
    - name:         "desktop"
      description:  "Desktop or tablet"

    - name:         "mobile"
      description:  "Mobile"

sites:
    - name:         "main"
      description:  "Main site"

languages:
    - name:         "nl"
      description:  "Dutch"
      locale:       "nl_NL.utf-8"

    - name:         "en"
      description:  "English"
      locale:       "en_GB.utf-8"


routeprefixes:
    - prefix:       "http://px4bmfw.twokings.eu/nl/"
      language:     "nl"
      site:         "main"
      target:       "desktop"
      aliases:
          - "http://www.pivotx.nl/"

    - prefix:       "http://px4bmfw.twokings.eu/"
      language:     "en"
      site:         "main"
      target:       "desktop"
      aliases:
          - "http://pivotx.com/"
          - "http://www.pivotx.com/"
          - "http://www.pivotx.eu/"

routes:
    - filter:       { target: "desktop", site: "main", language: "en" }
      pattern:      "_page/latest-news"
      public:       "latest-news"
      defaults:     { _rewrite: "main/(en)@archive/0000-00" }

    - filter:       { target: "desktop", site: "main", language: "nl" }
      pattern:      "_page/latest-news"
      public:       "laatste-nieuws"
      defaults:     { _rewrite: "main/(nl)@archive/0000-00" }

    - filter:       { target: "desktop", site: "main", language: "en" }
      pattern:      "archive/{yearmonth}"
      public:       "archive/{yearmonth}"
      defaults:     { _controller: "PivotXCoreBundle:Debug:showArchive" }
      requirements:
          yearmonth: "[0-9]{4}-[0-9]{2}"

    - filter:       { target: "desktop", site: "main", language: "nl" }
      pattern:      "archive/{yearmonth}"
      public:       "archief/{yearmonth}"
      defaults:     { _controller: "PivotXCoreBundle:Debug:showArchive" }
      requirements: 
          yearmonth:  "[0-9]{4}-[0-9]{2}"

