# some default content types.


# Entry
entry:
  name: "Entry"
  description: "Entries go here"
  extrafields: ""
  options: ""

# Page
page:
  name: "Page"
  description: "Pages go here"
  extrafields: ""
  options: ""

# Snippet / Widget
Recipe:
  name: "Recipe"
  description: "This is where we store the Recipes and Snippets."
  extrafields: ""
  options: ""

